variables:
- name: one
  value: initialValue 

jobs:
- job: Job3
  steps:
  - task: CmdLine@2
    displayName: 'Run Azure Storage Emulator'
    inputs:
      script: |
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init /server "(localdb)\MsSqlLocalDb"
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start