variables:
- name: one
  value: initialValue 

jobs:
- job: Job1
  displayName: Job1
  steps:
    - script: |
        echo ${{ variables.one }} # outputs initialValue
        echo $(one)
      displayName: First variable pass
    - bash: echo '##vso[task.setvariable variable=liveagency;isOutput=true]secondValue'
      displayName: Set new variable value
      name: test
    - script: |
        echo ${{ variables.one }} # outputs initialValue
        echo $(liveagency) # outputs secondValue
      displayName: Second variable pass

- job: Job2
  dependsOn: Job1
  displayName: Job2
  condition: and(succeeded(), eq(dependencies.Job1.outputs['test.liveagency'], 'secondValue'))
  steps:
    - script: |
        echo $(liveagency)
      displayName: With check

- job: Job3
  dependsOn: Job2
  displayName: Job3
  condition: and(succeeded(), eq(dependencies.Job2.outputs['test.liveagency'], 'secondValue'))
  steps:
    - script: |
        echo $(liveagency)
      displayName: With check